### ISSUE TITLE
transfer.toBalance 两个问题

### ISSUE THREAD

**Issue by movefreechen** [hpyer/node-easywechat#10]
1. 官方文档中参数是没有 sing_type的 request 方法中加了这个参数 这样会导致签名错误
2. spbill_create_ip 调用了一个 getServerIp 是一个 async function  应该加一个await

第一个问题建议在 options中加入 beforeSign(localParams):localParams  方法让开发者可以手动决定参数

**Comment by hpyer** [comment]
感谢反馈，请更新到版本2.6.9

对于第1个问题，重新去看了文档，貌似sing_type字段都是可选的，所以默认就都不传该字段了

**Comment by movefreechen** [comment]
> 感谢反馈，请更新到版本2.6.9
> 
> 对于第1个问题，重新去看了文档，貌似sing_type字段都是可选的，所以默认就都不传该字段了

这是官方接口的一个坑，我在微信小程序社区问答中找到的答案 实际上我尝试删除sign_type 后 接口就正常返回了

**Comment by hpyer** [comment]
> 这是官方接口的一个坑，我在微信小程序社区问答中找到的答案 实际上我尝试删除sign_type 后 接口就正常返回了

已修复该问题，现在默认不传sign_type字段了
