### ISSUE TITLE
想请教作者一下该库缓存access_token的原理

### ISSUE THREAD

**Issue by Choicelin** [hpyer/node-easywechat#14]
是使用文件缓存吗？

**Comment by hpyer** [comment]
默认是文件缓存。你可以利用 自定义模块 功能，改为想要的缓存方式。README里有讲：https://github.com/hpyer/node-easywechat#%E7%BC%93%E5%AD%98%E6%A8%A1%E5%9D%97cache

**Comment by Choicelin** [comment]
嗯嗯，自定义Redis那块确实看过，还有一点想请教的是，这个文件缓存对用户是透明的吧，也就是用户无需关心这些，只用关心业务处理对吗

**Comment by hpyer** [comment]
是的，配置个路径就行

**Comment by Choicelin** [comment]
感谢解答
