### ISSUE TITLE
关于不能发送客服图文消息的bug

### ISSUE THREAD

**Issue by michael51** [hpyer/node-easywechat#17]
位置:node_modules\node-easywechat\dist\Core\Messages\News.js

```
super({ items });
```

请修改为
```
 super({ articles:items }); 
```

**Comment by hpyer** [comment]
收到，晚点修复～

**Comment by hpyer** [comment]
你好，看了下代码，应该不存在这个问题。想问下你是在调用那个api方法的时候，需要实例化这个News对象？

`News`和`NewsItem`两个消息对象是用在被动回复消息功能的地方的，可以参考`node-easywechat-demo`里的写法 [https://github.com/hpyer/node-easywechat-demo/blob/2.x/app.js](https://github.com/hpyer/node-easywechat-demo/blob/2.x/app.js)

如果是群发消息，直接调用`app.broadcasting.sendNews()`方法，传入`mediaId`即可；

如果调用的是`app.broadcasting.sendMessage()`方法，则需要实例化`EasyWechat.Messages.Media`对象，如：
```js
let mediaId = 'xxx';
let media = new EasyWechat.Messages.Media(mediaId, 'mpnews');
app.broadcasting.sendMessage(media);
```

参考文档：[https://www.easywechat.com/5.x/official-account/broadcasting.html](https://www.easywechat.com/5.x/official-account/broadcasting.html)

**Comment by michael51** [comment]
是news这个函数。我使用你的，发出去腾讯提示空数据。empty news data。

![image](https://user-images.githubusercontent.com/31838439/160089198-8bb3f2ff-ad8c-4c7e-88b0-c95a43f095de.png)

其它格式是正常的。我检查了很久，发现官方给出的代码是。

```
{
    "touser": "oDxS26LVLMpLk1fdMnPi9JtsI0aw",
    "msgtype": "news",
    "news": {
        "articles": [{
            "title": "Happy Day",
            "description": "Is Really A Happy Day",
            "url": "URL",
            "picurl": "PIC_URL"
        }]
}
```

改成super({ articles:items });之后才正常，我反复测试了N次了。我现在是直接把你的包复制下来改的。
![image](https://user-images.githubusercontent.com/31838439/160086268-6ac38355-29bc-4a04-a03e-a864368dea58.png)

![image](https://user-images.githubusercontent.com/31838439/160089286-b95f3548-2211-4c1b-8dc9-0e48d097efa1.png)


```
		const news = new EasyWechat.Messages.News(
			[
				{
					'title': 'Happy Day Michael Ray',
					'description': 'Is Really A Happy Day',
					'url': 'URL',
					'picurl': 'PIC_URL'
				}]
		)`

			const info = await app
				.customer_service.message(news)
				.to('o-HwAjx3LGQmfjcIrFR4WmeJmHSo')
				.send()

```

**Comment by michael51** [comment]
是发送客服消息，不是被动的。而且不用传入NewsItem，直接用数组就可以。

**Comment by michael51** [comment]
这是官方给出的格式
```javascript
{
    "touser": "oDxS26LVLMpLk1fdMnPi9JtsI0aw",
    "msgtype": "news",
    "news": {
        "articles": [{
            "title": "Happy Day",
            "description": "Is Really A Happy Day",
            "url": "URL",
            "picurl": "PIC_URL"
        }]
}
```


利用你的插件的原始数据格式这样是可以发送成功的
```
const raw = new EasyWechat.Messages.Raw(` {
    "touser": "oDxS26LVLMpLk1fdMnPi9JtsI0aw",
    "msgtype": "news",
    "news": {
        "articles": [{
            "title": "Happy Day",
            "description": "Is Really A Happy Day",
            "url": "URL",
            "picurl": "PIC_URL"
        }]
    }
}`)

const status = await app
  .customer_service.message(raw)
  .to('oDxS26LVLMpLk1fdMnPi9JtsI0aw')
  .send()
```

**Comment by hpyer** [comment]
好的，我看代码是有兼容客服消息发送的，我调试下先～

**Comment by hpyer** [comment]
修复了，更新到v2.9.3版本看看
