### ISSUE TITLE
企业微信开放平台的bug

### ISSUE THREAD

**Issue by lshsuccess** [hpyer/node-easywechat#18]
企业微信开放平台的bug

1、provider_access_token 获取后缓存成功，但是下次使用时，虽然缓存中有，但是获取到的是undefined，BaseAccessToken.js的构造函数中加上以下语句就可以了，代码不是很熟悉，请大佬修复以下吧，

this.provider_access_token = info['provider_access_token'] || '';

2、截图中的缓存前缀不生效

![image](https://user-images.githubusercontent.com/22097038/164510487-4054cdb0-d149-4b6f-80f2-5958fcb2d084.png)

**Comment by hpyer** [comment]
收到，晚点修复~

**Comment by hpyer** [comment]
@lshsuccess 请更新到v2.9.4版本

**Comment by lshsuccess** [comment]
> @lshsuccess 请更新到v2.9.4版本

ok
