### ISSUE TITLE
企业微信登录回调错误

### ISSUE THREAD

**Issue by lshsuccess** [hpyer/node-easywechat#19]
企业微信登录回调 和 安装授权回调 使用了同一个回调地址配置，应该是不一样的才对
 
![image](https://user-images.githubusercontent.com/22097038/164743021-da2dd43c-e8b2-48d9-8015-3a02e8644e87.png)
![image](https://user-images.githubusercontent.com/22097038/164743111-8bc2ea9f-2cb4-41ae-8767-4fd6c3df911d.png)

**Comment by hpyer** [comment]
确实错了，`getLoginUrl`方法里应该用的是`redirect_uri_single`这个配置项～

**Comment by hpyer** [comment]
已修复，请更新到v2.9.5
