### ISSUE TITLE
第三方平调用 miniProgram 没有access_token

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#22]
第三方平调用 miniProgram 没有传access_token

**Comment by hpyer** [comment]
收到，晚点我看一下～

**Comment by ValueLan** [comment]
[https://github.com/hpyer/node-easywechat/pull/23](url)
已修复麻烦合并下

**Comment by ValueLan** [comment]
> 所有者

[https://github.com/hpyer/node-easywechat/pull/23](https://github.com/hpyer/node-easywechat/issues/url)
已修复合并下

**Comment by ValueLan** [comment]
> 收到，晚点我看一下～

测试用例没过，不知道咋搞，麻烦合并下，提交到npm上，我好更新你的包。

**Comment by hpyer** [comment]
更新到 v2.9.6 看下吧～

**Comment by hpyer** [comment]
请更新到 2.9.7，感谢反馈～
