### ISSUE TITLE
支付通知回调方法比较难用

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#27]
`    
newBody 必须是对象，还必须我传递 最简单是我传个req就可以了
let request = new Easewechat.Http.Request(req, newBody);

new Easewechat.Factory.Payment({
      app_id: storeInfo.appid,
      mch_id: storeInfo.mch_id,
      key: storeInfo.pay_key,
    });
  res.rebind('request', request);

`

**Comment by hpyer** [comment]
`Easewechat.Http.Request` 的第二个参数不是必填的，可以只传入 req

https://github.com/hpyer/node-easywechat#请求模块request

**Comment by ValueLan** [comment]
> 

如果我不给第二个参数就会报错
 这里content没值
https://github.com/hpyer/node-easywechat/blob/06ec55eff629a9182683b9e35cf49c40edff2a5a/src/Core/Http/Request.ts#L32
也没调用这个
https://github.com/hpyer/node-easywechat/blob/06ec55eff629a9182683b9e35cf49c40edff2a5a/src/Core/Http/Request.ts#L122


结果就是这一行的值是null
https://github.com/hpyer/node-easywechat/blob/06ec55eff629a9182683b9e35cf49c40edff2a5a/src/Payment/Notify/Handler.ts#L72

**Comment by hpyer** [comment]
这个我再排查一下吧，应该是不传第二个参数也可以的。。

另外，就是你用的是koa2还是express还是其它的web框架？

**Comment by ValueLan** [comment]
nestjs

**Comment by hpyer** [comment]
好的，我回头用这个框架试一下。估计是跟我文档里写的情况一样，`IncomingMessage`的 body流已经被 nestjs 读取了，，所以导致 Request 里再次读取的时候报错。。如果真是这种情况，那就必须要传第二个参数了。

**Comment by ValueLan** [comment]
看了你的公众号通知代码，我感觉支付100% 有bug

**Comment by hpyer** [comment]
nestjs 示例，更新到 2.10.2 后再看看～

```ts
import { Controller, Post, Req } from '@nestjs/common';
import { AppService } from './app.service';
import { Request } from 'express';
import * as NodeEasywechat from 'node-easywechat';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Post('/payNotify')
  async payNotify(@Req() req: Request): Promise<string> {
    let request = new NodeEasywechat.Http.Request(req);

    let app = new NodeEasywechat.Factory.Payment({
      appid: 'abc@123',
      key: '88888888888888888888888888888888',
      mch_id: '888888',
    });
    app.rebind('request', request);

    let response = await app.handlePaidNotify(async (message, setFail) => {
      console.log('message', message);
      return true;
    });

    return response.getContent().toString();
  }
}
```

**Comment by hpyer** [comment]
> nestjs 示例，更新到 2.10.2 后再看看～
> 
> ```ts
> import { Controller, Post, Req } from '@nestjs/common';
> import { AppService } from './app.service';
> import { Request } from 'express';
> import * as NodeEasywechat from 'node-easywechat';
> 
> @Controller()
> export class AppController {
>   constructor(private readonly appService: AppService) {}
> 
>   @Post('/payNotify')
>   async payNotify(@Req() req: Request): Promise<string> {
>     let request = new NodeEasywechat.Http.Request(req);
> 
>     let app = new NodeEasywechat.Factory.Payment({
>       appid: 'abc@123',
>       key: '88888888888888888888888888888888',
>       mch_id: '888888',
>     });
>     app.rebind('request', request);
> 
>     let response = await app.handlePaidNotify(async (message, setFail) => {
>       console.log('message', message);
>       return true;
>     });
> 
>     return response.getContent().toString();
>   }
> }
> ```

漏了测试用报文
```xml
<xml>
<foo>bar</foo>
<sign>834A25C9A5B48305AB997C9A7E101530</sign>
</xml>
```
