### ISSUE TITLE
3.3.4版本在调用.getServer().serve()时会出错。

### ISSUE THREAD

**Issue by zengyishou** [hpyer/node-easywechat#38]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/96757567/234820292-9b16a1f0-3833-40d0-a15f-1cd3989406df.png">
<img width="938" alt="image" src="https://user-images.githubusercontent.com/96757567/234820718-6306d5fc-bd30-407a-92e6-3bb997360691.png">

出错内容为：this.request.getQueryParams is not a function

**Comment by hpyer** [comment]
你这个是什么框架？

你确认 `this.ctx.req` 是可以拿到原始请求的吗？

**Comment by zengyishou** [comment]
使用的是midwayjs，上层框架是Koa，可以拿到IncomingMessage的。
<img width="730" alt="image" src="https://user-images.githubusercontent.com/96757567/234831778-81bc8339-ca5f-432b-bdbd-253ef017eae9.png">

**Comment by hpyer** [comment]
好的，晚点我测试下

**Comment by zengyishou** [comment]
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/96757567/234840761-0451abce-8fb1-4d44-8c4b-09f2190595bb.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/96757567/234840929-1072224c-99b7-4673-accf-0dc91287148f.png">
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/96757567/234841295-f91609ff-7699-4bdd-965f-437f7714b6e2.png">
在以上几处分别打了log，最终获得的

> this.request.getQueryParams

 是 

> undefined

 对框架结构还不是很熟悉，找不到具体原因。

**Comment by hpyer** [comment]
```ts
import { All, Controller, Inject } from '@midwayjs/core';
import { OfficialAccount, ServerRequest } from 'node-easywechat';
import { Context } from '@midwayjs/koa';

@Controller('/')
export class HomeController {

  @Inject()
  ctx: Context;

  @All('/')
  async home(): Promise<string> {
    const app = new OfficialAccount({
      app_id: '',
      secret: '',
      token: '',
      aes_key: '',
    });

    let request = await ServerRequest.createFromIncomingMessage(this.ctx.req);
    app.setRequest(request);

    const server = app.getServer();

    server.with(message => {
      console.log('message', message);
    });

    const response = await server.serve();

    return response.getBody().toString();
  }
}
```

我用上面这个测试脚本执行，没发现你反馈的问题。猜测还是 `this.ctx.req` 的问题，你再对照着检查一下看吧。

_测试用到的测试数据如下：_

**midwayjs:**

最新的3.x版本

**GET：**

`http://127.0.0.1:7001/?signature=9a39e983e5743d01e23507ad58ca3e90dbb9ebab&echostr=15947793626788132863&timestamp=1505801645&nonce=2830267549`

**POST：**

```xml
<xml>
<ToUserName><![CDATA[toUser]]></ToUserName>
<FromUserName><![CDATA[fromUser]]></FromUserName>
<CreateTime>1348831860</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[this is a test]]></Content>
<MsgId>1234567890123456</MsgId>
</xml>
```
