### ISSUE TITLE
请问cluster模式下access_token 怎么共享的？

### ISSUE THREAD

**Issue by mygoodidea** [hpyer/node-easywechat#4]
请问cluster模式下access_token 怎么共享的？

**Comment by hpyer** [comment]
建议存到redis等缓存里

**Comment by mygoodidea** [comment]
@hpyer node-easywechat是不是把access_token保存在本地文件的？
我在node的cluster模式下使用node-easywechat 和 koa 是不是可以共享token，不会出现token错乱的情况把？

**Comment by hpyer** [comment]
@mygoodidea 
默认是使用文件存储的
正常情况下，都需要另外跑个计划任务，来定时更新token，以避免在使用的时候因为token过期而导致并发去更新token的情况出现。这样业务逻辑中都是读取的操作，只要不出现文件锁死的情况，不会冲突对的。但是毕竟文件的读写相对缓存的读写是要慢的，所以还是建议你用redis等来缓存token。

要改用自定义缓存的话，可以自行实现`EasyWechat.CacheInterface`类（对应的文件`Core/Contracts/CacheInterface`），代码如下

```js
const EasyWechat = require('node-easywechat2');

class RedisCache extends EasyWechat.CacheInterface {
    // TODO: 实现对应的方法
}

let config = {};

let app = EasyWechat.Factory.getInstance('OfficialAccount', config);
app.cache = new RedisCache;

// TODO: 其它业务逻辑
```

**Comment by mygoodidea** [comment]
@hpyer 明白了，谢谢你的回答。
其实php的easywechat应该也是有并发问题的，所以还是另起一个任务更新token比较好
