### ISSUE TITLE
2.x 版本有直接发起请求的接口嘛？

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#43]
微信第三方新增了备案需求，有没有直接发起请求的方法

**Comment by hpyer** [comment]
https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/record/applyIcpFiling.html

这个接口吗？目前没有添加

**Comment by ValueLan** [comment]
我意思是可以新增个 全局的请求  以公众号为例子 这样新的改动就不需要再写了
 ```
let officialAccount= new OfficialAccount({})
officialAccount.post('https://weixin/...', {})
officialAccount.get('https://weixi',{})
```

**Comment by hpyer** [comment]
明白了，晚点加一下

**Comment by hpyer** [comment]
`v2.13.0` 版本已添加相关api，请看使用说明：https://github.com/hpyer/node-easywechat/tree/2.x#发起请求

**Comment by ValueLan** [comment]
非常感谢
