### ISSUE TITLE
小程序支付，生成参数错误

### ISSUE THREAD

**Issue by nxboo** [hpyer/node-easywechat#45]
小程序端调用返回错误信息：
requestPayment:fail parameter error: parameter.timeStamp should be String instead of Number

小程序文档：
https://developers.weixin.qq.com/miniprogram/dev/api/payment/wx.requestPayment.html
![WX20231115-162012@2x](https://github.com/hpyer/node-easywechat/assets/4253172/214ccca5-5519-4a41-9b1f-0d6e8f3feb16)

**Comment by hpyer** [comment]
收到，晚点修复

**Comment by hpyer** [comment]
请更新到 `v3.5.4` 版本

**Comment by nxboo** [comment]
@hpyer 牛啊，相应这么快

**Comment by hpyer** [comment]
主要还是感谢你的反馈～ 😄
