### ISSUE TITLE
2x版本请问开放平台 如何解密消息

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#48]
2 x版本 开放平台解密bug
https://github.com/hpyer/node-easywechat/blob/92e5b5d8740fb95fbfb7258c58657c5f47970be1/src/Core/ServerGuard.ts#L147
执行到这一行了

https://github.com/hpyer/node-easywechat/blob/92e5b5d8740fb95fbfb7258c58657c5f47970be1/src/OpenPlatform/Server/OpenPlatformGuard.ts#L15

没有执行到预期的
https://github.com/hpyer/node-easywechat/blob/92e5b5d8740fb95fbfb7258c58657c5f47970be1/src/Core/ServerGuard.ts#L179

请问这样设计有啥目的吗，能否修复该bug

**Comment by ValueLan** [comment]
这个函数代码主要用于广播，是否可以在下面新增如下代码
我就不修改了，麻烦改好更新下NPM谢谢
return super.resolve();
https://github.com/hpyer/node-easywechat/blob/92e5b5d8740fb95fbfb7258c58657c5f47970be1/src/OpenPlatform/Server/OpenPlatformGuard.ts#L25C13-L25C13

**Comment by hpyer** [comment]
好的，白天有点忙，晚点我处理下

**Comment by hpyer** [comment]
我这里测试了下，接受开放平台的消息推送应该没什么问题呀。

你是不是用这个来接受公众号或者小程序的推送消息了？

**Comment by ValueLan** [comment]
是的这个是开放平台，可以接收信息，但是你没有调用父类的resolve

**Comment by ValueLan** [comment]
你设计 server.hanlder(() =>{ })的初衷是把回调保存起来 在  server.server()的时候调用，
但是因为你没super.resolve() 所以就会出现hanlder里面的方法不执行
我希望你可以把这一行代码
https://github.com/hpyer/node-easywechat/blob/92e5b5d8740fb95fbfb7258c58657c5f47970be1/src/OpenPlatform/Server/OpenPlatformGuard.ts#L25C13-L25C13

return new Response(Buffer.from(ServerGuard.SUCCESS_EMPTY_RESPONSE));
改成这样
return super.resolve();

**Comment by hpyer** [comment]
emmm...你肯定是用开放平台的server去接收代理公众号或者代理小程序的推送消息了。

开放平台推送的消息总共就4种类型，​ 授权成功 authorized、授权更新 updateauthorized、授权取消 unauthorized、VerifyTicket component_verify_ticket，这四种类型的消息都有 `InfoType` 字段的。而没有这个字段的，都不做处理，直接返回成功。

你要接收代理公众号的推送消息的话，应该是要另外写一个接口，然后调用开放平台实例的`officialAccount()`方法去获取到公众号实例，再用公众号实例的server去处理消息。代码如下：

```js
const openplatform = new EasyWechat.Factory.OpenPlatform({});

const oaId = ''; // 可以从微信推送的回调地址中解析出来
const oaRefreshToken = ''; // 完成公众号授权后获取到的

const oaApp = openplatform.officialAccount(oaId, oaRefreshToken);

let request = new EasyWechat.Http.Request(ctx.req);
oaApp.rebind('request', request);

oaApp.server.push((message) => {
    console.log(message);
});

const response = await oaApp.server.serve();

```

参考文档：
* https://easywechat.com/5.x/open-platform/authorizer-delegate.html
* https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/Before_Develop/Authorization_Process_Technical_Description.html

**Comment by ValueLan** [comment]
按照你这个方法去写会报错
Error: Invalid appId
/dist/Core/Encryptor.js:63:19
如果按照我方法去改，就没问题，当然能解决就好

**Comment by hpyer** [comment]
好的，我明天早上再查一下

**Comment by hpyer** [comment]
> 按照你这个方法去写会报错 Error: Invalid appId /dist/Core/Encryptor.js:63:19 如果按照我方法去改，就没问题，当然能解决就好

我这边测试了，用我上面的写法，消息解密是没问题的。用的版本是`2.13.1`，要不你再查一下代码。这里提供我的测试代码：

**授权页** URL：`http://example.com/wxopen/auth`
```js
const app = new EasyWechat.Factory.OpenPlatform({});
let url = await app.getPreAuthorizationUrl('http://example.com/wxopen/auth/callback')
// 前端页面生成链接提供给用户点击，如：<a href="${url}">发起授权</a>
```

**授权回调页** URL：`http://example.com/wxopen/auth-callback`
```js
const app = new EasyWechat.Factory.OpenPlatform({});
let auth_code = ctx.query.auth_code; // 从querystring中获取
let res = await app.handleAuthorize(auth_code);
// 从res中获取 authorizer_refresh_token 并和 authorizer_appid 一起保存，以便后续使用
// 参考文档：https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/ThirdParty/token/authorization_info.html
// 提示授权成功，并跳转相关页面
```

**开放平台服务端接口** URL：`http://example.com/wxopen/server`
```js
const app = new EasyWechat.Factory.OpenPlatform({});
let request = new EasyWechat.Http.Request(ctx.req);
app.rebind('request', request);
app.server.push(async function (message) {
  console.log(ctx.path, message);
});
let response = await app.server.serve();
// 输出结果 response.getContent().toString()
// 这个接口的主要是用于接收微信推送的 component_verify_ticket，node-easywechat会自动缓存并再换取component_access_token的时候使用，这个过程对于开发者来说是无感的
// 如果你的业务需要对于完成授权、取消授权等事件进行处理的话，可以在上面的回调中完成。
```

**代理公众号的服务端接口** URL：`http://example.com/wxopen/authorizer/$APPID$` (微信在发送请求的时候，会把`$APPID$`替换会对应公众号的appid)
```js
const app = new EasyWechat.Factory.OpenPlatform({});

let authorizer_id = ''; // 从请求地址中解析出 appid
let refreshToken = ''; // 授权回调页保存的 authorizer_refresh_token
const oaApp = app.officialAccount(authorizer_id, refreshToken);
oaApp.server.push(async function (message) {
  console.log(ctx.path, message);
});
let response = await oaApp.server.serve();
// 输出结果 response.getContent().toString()
```
