### ISSUE TITLE
2.x版本特约商户进件 能否完善

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#49]
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter11_1_1.shtml

**Comment by hpyer** [comment]
2.x是不支持微信支付的v3版本api的（3.x支持），主要是php版的easywechat就是不支持的（那时候还没有v3的api），后续也一直没增加，所以我也没去添加这个功能。

如果你这边确实升级3.x比较麻烦的话，我这两天增加下吧，不过就不封装API了。就用getClient()之后，直接去发请求了。

**Comment by ValueLan** [comment]
嗯我看看能否升级，应该也不是很多
