### ISSUE TITLE
3.x 模式 utils.codeToSession  未实现第三方模式

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#54]
https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/login/thirdpartyCode2Session.html

**Comment by ValueLan** [comment]
该问题非刚需，可通过其他方法实现

**Comment by hpyer** [comment]
请更新到 `v3.5.7`，Utils增加了`thirdpartyCode2Session`方法

**Comment by ValueLan** [comment]
个人感觉这样新增不太好，
个人建议
let op = new OpenPlatform()

op.getMiniApp  这方法里操作
getMiniApp = function(){
  ...
  let mp = new MiniApp
  mp.setOpenPlatform(this)
 通过判断是否有第三放来实现，
}

**Comment by hpyer** [comment]
你这样其实也就相当于重写code2Session，我本来有想过的，但是又怕原方法还要用，所以～

**Comment by hpyer** [comment]
现在想想，好想直接重写这个方法也没问题，既然都通过开放平台来获取小程序实例了，那肯定就是代理的模式。。真要用原方法，反正直接new原来的MiniApp就行了～

我改成用同一个方法名好了～
