### ISSUE TITLE
微信支付未实现getValidator

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#56]
https://easywechat.com/6.x/pay/index.html

**Comment by hpyer** [comment]
请更新到 `v3.5.7`。我这只能跑测试用例调试。麻烦你这边真实环境测试一下，给个反馈，谢谢～

**Comment by ValueLan** [comment]
````
node_modules/node-easywechat/dist/Types/global.d.ts:78:11 - error TS2503: Cannot find namespace 'axiosRetry'.

78   retry?: axiosRetry.IAxiosRetryConfig;


Request'.
  Type 'ServerRequestInterface' is missing the following properties from type 'Request': headers, protocal, content, setHeaders, and 3 more.

249       let bool = app.getValidator().validate(app.getRequest())
validate 类型和 getRequest类型不一致 

```

**Comment by hpyer** [comment]
emmm.....好吧，我没在ts项目里测试～～

**Comment by ValueLan** [comment]
// API 请求示例
$response = $app->getClient()->postJson("v3/pay/transactions/jsapi", [...]);

try{
    $app->getValidator()->validate($response->toPsrResponse()); // 这个是否未实现
   // 验证通过
} catch(Exception $e){
  // 验证失败
}

**Comment by ValueLan** [comment]
看了下源码，请问V2支付验证和V3是一样吗？
还是需要我来测试下

**Comment by hpyer** [comment]
> // API 请求示例 $response = $app->getClient()->postJson("v3/pay/transactions/jsapi", [...]);
> 
> try{ $app->getValidator()->validate($response->toPsrResponse()); // 这个是否未实现 // 验证通过 } catch(Exception $e){ // 验证失败 }

我知道是用在哪里，只是类型搞错了～

**Comment by hpyer** [comment]
> 看了下源码，请问V2支付验证和V3是一样吗？ 还是需要我来测试下

我记得v2的通知是没有这个校验的，只需要判断内容里面是否成功就行。可以官方文档再查一下看。

**Comment by ValueLan** [comment]
通知发送内容我觉得应该都一样，
主要是咱们3.x版本，需要生成证书
但是如果验证应该不用生成的证书把
只需要 key和cert 把

**Comment by hpyer** [comment]
验证请求，是要用到 platform_certs 参数配置的证书的（也就是用工具下载的证书）

**Comment by hpyer** [comment]
更新 3.5.8 再看下

**Comment by ValueLan** [comment]
OK
1、还是想您实现  https://github.com/hpyer/node-easywechat/issues/57 这个方法 要不然我感觉我是实力，实现还是有点困难，蛮多其他人估计也 一样
2、response.toPsrResponse 未实现
3、我看了下V2版本，其实是有验证的
https://github.com/hpyer/node-easywechat/blob/92e5b5d8740fb95fbfb7258c58657c5f47970be1/src/Payment/Notify/Handler.ts#L96

**Comment by hpyer** [comment]
> OK
> 1、还是想您实现  https://github.com/hpyer/node-easywechat/issues/57 这个方法 要不然我感觉我是实力，实现还是有点困难，蛮多其他人估计也 一样
> 2、response.toPsrResponse 未实现
> 3、我看了下V2版本，其实是有验证的
> https://github.com/hpyer/node-easywechat/blob/92e5b5d8740fb95fbfb7258c58657c5f47970be1/src/Payment/Notify/Handler.ts#L96

1、57那个问题我觉得不是很急，就暂时没加。
2、有的，叫toHttpResponse，psr是PHP的标准，就不用那个名字了，虽然是参考实现的
3、我晚上再看一下怎么验证吧，签名的算法是有的

**Comment by ValueLan** [comment]
感谢，其实我这边只要加上验证，就可以全部替换3.x版本，并生产跑了
没有实现 #57 我这边暂时也无法测 getValidator().validate()   主要我看那个java工具，感觉挺麻烦的

**Comment by hpyer** [comment]
更新到 3.5.9，增加了 validateV2 方法，参数是回调函数的参数message

用法：

```js
const app = new Pay({});
const server = app.getServer();
server.handlePaid((message, next) => {
  try {
    app.getValidator().validateV2(message);
    // 成功
  }
  catch (e) {
    // 失败
  }
  return next(message);
});
```

**Comment by ValueLan** [comment]
```
 const app = new Pay({});
const server = app.getServer();
server.handlePaid((message, next) => {
  try {
    app.getValidator().validateV2(message);  //这个message类型不一样
    // 成功
  }
  catch (e) {
    // 失败
  }
  return next(message);
});

```
如下才可以

```
 const app = new Pay({});
const server = app.getServer();
server.handlePaid(async(message, next) => {
  try {
   await  app.getValidator().validateV2(await serve.getRequestMessage());  //这个message类型不一样
    // 成功
  }
  catch (e) {
    // 失败
  }
  return next(message);
});

```

**Comment by ValueLan** [comment]
```` 
1、
server.handlePaid  无法适用于V2通知

Invalid request body.
     at Server.<anonymous> (node_modules/node-easywechat/dist/Pay/Server.js:69:23)
     at Generator.next (<anonymous>)
     at node_modules/node-easywechat/dist/Pay/Server.js:8:71
     at new Promise (<anonymous>)
     at __awaiter (node_modules/node-easywechat/dist/Pay/Server.js:4:12)
     at Server.getRequestMessage

2、 V3      serve.handlePaid(async (msg, next) => {  msg类型 和 app.getValidator().validate(这个类型) 不一致
 

````

**Comment by hpyer** [comment]
> ```
> 1、
> server.handlePaid  无法适用于V2通知
> 
> Invalid request body.
>      at Server.<anonymous> (node_modules/node-easywechat/dist/Pay/Server.js:69:23)
>      at Generator.next (<anonymous>)
>      at node_modules/node-easywechat/dist/Pay/Server.js:8:71
>      at new Promise (<anonymous>)
>      at __awaiter (node_modules/node-easywechat/dist/Pay/Server.js:4:12)
>      at Server.getRequestMessage
> 
> 2、 V3      serve.handlePaid(async (msg, next) => {  msg类型 和 app.getValidator().validate(这个类型) 不一致
>  
> ```

1、getServer 之前是不是没 setRequest ？
```js
const app = new Pay({});

let request = await ServerRequest.createFromIncomingMessage(ctx.req);
app.setRequest(request);

const server = app.getServer();

server.handlePaid(async(message, next) => {
  try {
    // message 和 serve.getRequestMessage() 应该是一样的类型的，可能是类型推到有问题
    await  app.getValidator().validateV2(await serve.getRequestMessage());
    // 成功
  }
  catch (e) {
    // 失败
  }
  return next(message);
});

```

2、V3的验证，validate 的参数是 request 对象，不是message

**Comment by ValueLan** [comment]
问题1 微信 支付 v2 是不是xml格式 咱们解析代码如下

https://github.com/hpyer/node-easywechat/blob/eadc70ef4c09bdf834945cc1b65a2711d6148269/src/Pay/Server.ts#L56

问题2应该是我的问题，

**Comment by hpyer** [comment]
v2都是xml格式的

不过，这个地方获取的时候已经是对象了，，因为 `let request = await ServerRequest.createFromIncomingMessage(ctx.req);` 这一步封装的时候，把xml给解析了

另，`server.handlePaid(async(message, next) => {` 这里的message类型推到确实有问题，推到成message的基类了

**Comment by ValueLan** [comment]
验证问题我在排查下

**Comment by ValueLan** [comment]
问题1的原因如下
https://github.com/hpyer/node-easywechat/blob/eadc70ef4c09bdf834945cc1b65a2711d6148269/src/Pay/Server.ts#L25

v2 没有
['resource']['ciphertext']
https://github.com/hpyer/node-easywechat/blob/eadc70ef4c09bdf834945cc1b65a2711d6148269/src/Pay/Server.ts#L69

**Comment by hpyer** [comment]
请更新3.5.10再测试一下。框架会自行判断是否v2的消息(xml格式)并解析，无需额外处理。
