### ISSUE TITLE
特殊字段加密能否集成到utils 里去

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#58]
特殊字段加密能否集成到utils 里去
如 姓名、银行卡 等加密需要使用该方法
https://github.com/hpyer/node-easywechat/blob/1521d7c6c96a10a23bb6fcf83f98bb5e16fd9b67/src/Core/Support/RSA.ts#L44

**Comment by ValueLan** [comment]
改加密即如下把
https://pay.weixin.qq.com/docs/partner/development/interface-rules/sensitive-data-encryption.html

**Comment by hpyer** [comment]
请更新到 `v3.5.7`，Utils增加了`encrypt`、`decrypt`两个方法
