### ISSUE TITLE
微信支付设置http.throw = false 无效

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#59]
因为请求微信支付，返回500 或者400 等状态，需要如下才能拿到500的body

``

try {
let res =  await  client.post ('xx', {})
} catch(e) {
      console.log(e.response.data)
}
``

**Comment by ValueLan** [comment]
博主辛苦了，暂时解决这些问题，我这边应该都能跑通了

**Comment by hpyer** [comment]
请更新到 `v3.5.7`
