### ISSUE TITLE
[bug] 支付统一下单错误

### ISSUE THREAD

**Issue by fanybook** [hpyer/node-easywechat#6]
我在本地改了一下库，终于下单成功

1. Payment\Order\Client.js 的 unify 这里，应该改成这样吧，非签约时地址有问题
```js
            if (isContract) {
                params['contract_appid'] = this.app['config'].app_id;
                params['contract_mchid'] = this.app['config'].mch_id;
                params['request_serial'] = params['request_serial'] || Utils_1.getTimestamp();
                params['contract_notify_url'] = params['contract_notify_url'] || this.app['config'].contract_notify_url;

                return this.request(this.wrap('pay/contractorder'), params);
            }

            return this.request(this.wrap('pay/unifiedorder'), params);
```
2. Payment\Core\BaseClient.js 的 request 这里，默认的 md5 应该改成大写，否则会报 `{ return_code: 'FAIL', return_msg: '签名类型不支持' }`
```js
localParams['sign_type'] = localParams['sign_type'] || 'MD5';
```

**Comment by hpyer** [comment]
感谢反馈，下个版本修复～

**Comment by vipluosong** [comment]
统一支付报“ Error: Request failed with status code 404”，看日志请求的地址“https://api.mch.weixin.qq.com/sandboxnew/pay/getsignkey”

**Comment by vipluosong** [comment]
统一下单 在小程序端调起微信支付的时候 提示“支付验证签名失败”
`
 const res: any = await Payment.order.unify(data);
    console.log('------------------res', res, data);
    return {
      appId: res.appid,
      timeStamp: ceil(Date.now() / 1000).toString(),
      nonceStr: res.nonce_str,
      package: 'prepay_id=' + res.prepay_id,
      signType: 'RSA',
      paySign: res.sign,
    };


最终的返回结果：

code: 1000
data: {
  nonceStr: "kiAQasGPzRCQRtwT"
  package: "prepay_id=wx232316527919487ef071b1760787f40000"
  paySign: "6401BA5389F77F53662247288806BD3F"
  signType: "MD5"
}
timeStamp: "1663946213"
message: "success"
`

微信官方文档： https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_5_4.shtml

**Comment by hpyer** [comment]
> 统一下单 在小程序端调起微信支付的时候 提示“支付验证签名失败” ` const res: any = await Payment.order.unify(data); console.log('------------------res', res, data); return { appId: res.appid, timeStamp: ceil(Date.now() / 1000).toString(), nonceStr: res.nonce_str, package: 'prepay_id=' + res.prepay_id, signType: 'RSA', paySign: res.sign, };
> 
> 最终的返回结果：
> 
> code: 1000 data: { nonceStr: "kiAQasGPzRCQRtwT" package: "prepay_id=wx232316527919487ef071b1760787f40000" paySign: "6401BA5389F77F53662247288806BD3F" signType: "RSA" } timeStamp: "1663946213" message: "success" `
> 
> 微信官方文档： https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_5_4.shtml

@vipluosong 2.x用的是 微信支付v2 版本的接口，文档地址：https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=9_1

**Comment by vipluosong** [comment]
我的调用流程有问题，
反馈一个建议：JssdkClient.d.ts 的 sdkConfig 方法返回的timestamp字段应该改为timeStamp，不然会导致小程序调起支付失败！

**Comment by hpyer** [comment]
> 我的调用流程有问题， 反馈一个建议：JssdkClient.d.ts 的 sdkConfig 方法返回的timestamp字段应该改为timeStamp，不然会导致小程序调起支付失败！

看下easywechat的使用说明吧：https://easywechat.com/5.x/payment/jssdk.html#生成支付-js-配置

小程序支付调用的是`bridgeConfig`，`sdkConfig`是供 jssdk 调用的
