### ISSUE TITLE
微信 加密方式错误，注意该问题不是bug，但是很多人会犯错

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#65]
https://github.com/hpyer/node-easywechat/blob/04ae22158f81aa223d653bf4936214fd8499491c/src/Core/Support/RSA.ts#L49

hashType='sha1'

**Comment by ValueLan** [comment]
个人建议 这里， 改写一下默认为sha1
https://github.com/hpyer/node-easywechat/blob/04ae22158f81aa223d653bf4936214fd8499491c/src/Pay/Encryptor.ts#L21

**Comment by hpyer** [comment]
好的，微信是真坑啊～😂
