### ISSUE TITLE
nextjs 中报错

### ISSUE THREAD

**Issue by crazyming9528** [hpyer/node-easywechat#67]
async function handle(
    req: NextApiRequest,
    { params }: { params: { path: string[] } },
) {

    let officialAccountConfig: OfficialAccountConfig = {
      };//公众号配置

      const app = new OfficialAccount(officialAccountConfig);
      const request = await ServerRequest.createFromIncomingMessage(req);
      app.setRequest(request);
      const serve = app.getServer();

}

在 nextjs 中 执行到 const request = await ServerRequest.createFromIncomingMessage(req); 报错：TypeError: argument stream must be a stream

**Comment by hpyer** [comment]
`req: NextApiRequest` 类型错误，需要的是 `express` 的 `Request`

```ts
import { Request } from 'express';

async function handle( req: Request, { params }: { params: { path: string[] } }) {
  // ...
}
```

**Comment by crazyming9528** [comment]
> `req: NextApiRequest` 类型错误，需要的是 `express` 的 `Request`
> 
> ```ts
> import { Request } from 'express';
> 
> async function handle( req: Request, { params }: { params: { path: string[] } }) {
>   // ...
> }
> ```

我看createFromIncomingMessage 的 reg 参数类型是IncomingMessage哇，NextApiRequest 是继承自IncomingMessage

**Comment by crazyming9528** [comment]
> `req: NextApiRequest` 类型错误，需要的是 `express` 的 `Request`
> 
> ```ts
> import { Request } from 'express';
> 
> async function handle( req: Request, { params }: { params: { path: string[] } }) {
>   // ...
> }
> ```

我看createFromIncomingMessage 的 req 参数类型是IncomingMessage哇，NextApiRequest 是继承自IncomingMessage

**Comment by crazyming9528** [comment]
哎，我不小心吧issues关了

**Comment by hpyer** [comment]
node里的流只能读取一次，既然报错提示“TypeError: argument stream must be a stream”，那说明NextApiRequest已经把请求的body流给读取了，所以才会报异常。

**Comment by crazyming9528** [comment]
> node里的流只能读取一次，既然报错提示“TypeError: argument stream must be a stream”，那说明NextApiRequest已经把请求的body流给读取了，所以才会报异常。

按你文档的方法 第二个参数传入了 body 也没用。我看看源码

**Comment by crazyming9528** [comment]
<img width="922" alt="image" src="https://github.com/hpyer/node-easywechat/assets/34561818/e052fc6c-07e4-456e-b7b8-3ff56e69eacf">
这个问题解决了，但有另一个问题，server.serve() 返回的 Response实例 是自己实现的Response类，但  nextjs 要求 return  一个 nodejs 的 Response 或者  NextResponse，只能先这样处理了
<img width="877" alt="image" src="https://github.com/hpyer/node-easywechat/assets/34561818/66f090a4-20b4-4313-b9aa-a4b7b44c2bbb">

**Comment by hpyer** [comment]
> <img alt="image" width="922" src="https://private-user-images.githubusercontent.com/34561818/309137704-e052fc6c-07e4-456e-b7b8-3ff56e69eacf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjUyOTEsIm5iZiI6MTcwOTI2NDk5MSwicGF0aCI6Ii8zNDU2MTgxOC8zMDkxMzc3MDQtZTA1MmZjNmMtMDdlNC00NTZlLWI3YjgtM2ZmNTZlNjllYWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDAzNDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYWY3ZjA2MzgxN2I3ZjdmNWI3ZDM1YTYwNTQ4MWZmYTc3ZDRiOWJjZTgzZTgzMjY4YjJjMmNlYTRiZjFjNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PVS6K_uxKlO_zq18hcNgt95xcMuzQv-HiWLyMuzl6xI"> 这个问题解决了，但有另一个问题，server.serve() 返回的 Response实例 是自己实现的Response类，但 nextjs 要求 return 一个 nodejs 的 Response 或者 NextResponse，只能先这样处理了 <img alt="image" width="877" src="https://private-user-images.githubusercontent.com/34561818/309138649-66f090a4-20b4-4313-b9aa-a4b7b44c2bbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjUyOTEsIm5iZiI6MTcwOTI2NDk5MSwicGF0aCI6Ii8zNDU2MTgxOC8zMDkxMzg2NDktNjZmMDkwYTQtMjBiNC00MzEzLWI5YWEtYTRiN2I0NGMyYmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDAzNDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZDgxNzgxNWQ0Yjk0MTYwZTcyNzY0ZDM0MWU0N2YwNDUyYWFiMGU5ODUyODVkMTQ2OGY5NWQ1ODQ1ZjhiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q7dnXJ5yZaw9Dmd1LX3YGd0AQKdlVp89-ax7wp5PC4g">

工具包不可能知道应用层用了什么框架，所以只能是这种方式，自行封装所需的返回类型。。

**Comment by hpyer** [comment]
```ts
import { NextApiRequest, NextApiResponse } from 'next';
import { OfficialAccount, ServerRequest } from 'node-easywechat';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {

    const app = new OfficialAccount({
        // config
    });

    const request = await ServerRequest.createFromIncomingMessage(req, req.body);
    app.setRequest(request);

    const server = app.getServer();
    server.with(function (message) {
        console.log('message', message);
    });
    let response = await server.serve();

    res.end(response.getBody().toString());
}
```

今天重新写了个demo测试了一下，应该是没问题的。issue长时间没跟进，就先关闭了，如还有问题请再开issue。
