### ISSUE TITLE
Failed to decode request contents。

### ISSUE THREAD

**Issue by crazyming9528** [hpyer/node-easywechat#68]
向公众号发送消息 触发createFromRequest 报错：Failed to decode request contents。

看起来是 originContent 的值不正确？调试结果是："[object Request]"
![image](https://github.com/hpyer/node-easywechat/assets/34561818/dbd6523d-4c3f-4461-b8f3-4c6272a1c691)

**Comment by hpyer** [comment]
收到，晚点我查一下

**Comment by hpyer** [comment]
![WX20240301-145039@2x](https://github.com/hpyer/node-easywechat/assets/1290392/a415ec59-b718-4d2e-ade2-309c328638e2)


我这试了下，消息解密没问题的。你检查下配置项`token`和`aes_key`是否设置正确。

**Comment by hpyer** [comment]
issue长时间没跟进，就先关闭了，如还有问题请再开issue。
