### ISSUE TITLE
请使用node-easywechat代替node-easywechat2

### ISSUE THREAD

**Issue by hpyer** [hpyer/node-easywechat#7]
以前对npm的包发布不太了解，后来才知道是其实可以给版本打标签的，这样就可以区别出每个大版本了。

主要也是自己也懒，一直拖着没去改这个名称，随着时间推移，越来越觉得 `node-easywechat` 这个名称可能更好点，要是放弃了也挺可惜的。思来想去还是觉得废弃 `node-easywechat2` 好点～

So，以后请大家还是用 `node-easywechat` 吧～

最新版本： `npm install node-easywechat`

之前的 1.x 版本： `npm install node-easywechat@first`

**Comment by overtrue** [comment]
项目不错哦，有几个建议：

1. https://semver.org/ 这个建议看一下，小心发版不规范导致用户项目崩掉
2. 名称应该是 EasyWeChat 而不是 EasyWechat哈哈
3. 虽然 w7corp/easywechat 是归属微擎了，但还是我在维护哈

加油 💪🏻

**Comment by hpyer** [comment]
> 项目不错哦，有几个建议：
> 
> 1. https://semver.org/ 这个建议看一下，小心发版不规范导致用户项目崩掉
> 2. 名称应该是 EasyWeChat 而不是 EasyWechat哈哈
> 3. 虽然 w7corp/easywechat 是归属微擎了，但还是我在维护哈
> 
> 加油 💪🏻

感谢大神的建议和鼓励，我会尽快调整，以后也会继续维护好项目的～ 😉
