### ISSUE TITLE
公众号授权域名不够用

### ISSUE THREAD

**Issue by Zch123** [hpyer/node-easywechat#71]
可不可以设置自定义的url去获取登录授权code，就是说自己搞一个登录授权中间件，在使用该sdk的时候，获取授权code请求的是自己的中间件url，而不是微信官方的。

**Comment by hpyer** [comment]
怎么可能呢。访问你自己的url，微信客户端都不会进入授权逻辑。如果让你不访问微信的授权地址，都能拿到code，那对于微信来说，安全性何在？

**Comment by mygoodidea** [comment]
> 怎么可能呢。访问你自己的url，微信客户端都不会进入授权逻辑。如果让你不访问微信的授权地址，都能拿到code，那对于微信来说，安全性何在？

我猜他是想自己mock微信授权服务,用来测试

**Comment by Zch123** [comment]
这是一种针对授权域名不够用的方案啊，做一个微信登录的中间件，所有的微信登录都是去请求这个中间件的，然后中间件再原样返回给请求方。我现在提出的就是希望可以在登录授权的时候可以自定义url

**Comment by Zch123** [comment]
> 怎么可能呢。访问你自己的url，微信客户端都不会进入授权逻辑。如果让你不访问微信的授权地址，都能拿到code，那对于微信来说，安全性何在？

我的意思是，在授权域名不够用下，就得使用授权中间件，中间件去发起微信的授权，然后再把微信返回的数据原样返回请求方。所有我希望在你这个sdk中可以自定义登录授权url，这样的话，我使用sdk的使用就是请求我的中间件发起授权登录，中间件再向微信发起授权，最后在sdk拿到的结果是中间件返回的微信原样数据

**Comment by hpyer** [comment]
> 我的意思是，在授权域名不够用下，就得使用授权中间件，中间件去发起微信的授权，然后再把微信返回的数据原样返回请求方。所有我希望在你这个sdk中可以自定义登录授权url，这样的话，我使用sdk的使用就是请求我的中间件发起授权登录，中间件再向微信发起授权，最后在sdk拿到的结果是中间件返回的微信原样数据

我所理解逻辑是这样，你看下对不对：

- A向B发起授权请求（携带自定义的唯一标识）
- B（中间件）跳转微信授权地址
- 微信认证完回调B
- B拿到code后请求微信获得用户信息（这里就可以根据唯一标识做缓存），然后携带唯一标识再跳转回A的回调地址
- A根据B传的标识，向B请求获得用户信息

如果是这样，那A这里完全不需要用到这个包啊

**Comment by Zch123** [comment]
> > 我的意思是，在授权域名不够用下，就得使用授权中间件，中间件去发起微信的授权，然后再把微信返回的数据原样返回请求方。所有我希望在你这个sdk中可以自定义登录授权url，这样的话，我使用sdk的使用就是请求我的中间件发起授权登录，中间件再向微信发起授权，最后在sdk拿到的结果是中间件返回的微信原样数据
> 
> 我所理解逻辑是这样，你看下对不对：
> 
> * A向B发起授权请求（携带自定义的唯一标识）
> * B（中间件）跳转微信授权地址
> * 微信认证完回调B
> * B拿到code后请求微信获得用户信息（这里就可以根据唯一标识做缓存），然后携带唯一标识再跳转回A的回调地址
> * A根据B传的标识，向B请求获得用户信息
> 
> 如果是这样，那A这里完全不需要用到这个包啊

这里B（中间件）跳转微信授权地址，微信认证完回调B，然后B将微信回调的数据原样返回给A，A拿到code后请求微信获得用户信息。所以你这个sdk如果能自定义一个授权url地址的话，就可以调用中间件拿code了，这样域名限制也不存在了

**Comment by hpyer** [comment]
> 这里B（中间件）跳转微信授权地址，微信认证完回调B，然后B将微信回调的数据原样返回给A，A拿到code后请求微信获得用户信息。所以你这个sdk如果能自定义一个授权url地址的话，就可以调用中间件拿code了，这样域名限制也不存在了

这需求暂时不考虑增加，应该用到的人不会很多。不过，还是给你个实现你需求的方法吧。

首先，继承 `node-socialite/dist/Providers/WeChat.js`，并重写相关方法。或者，参考 `node-socialite` 的[文档](https://github.com/hpyer/node-socialite#添加自定义服务商) 实现一个自定义provider

其次，OfficialAccount 实例有一个 `setOAuthFactory` 方法，可以创建自定义的provider，大概的代码如下：

```js
import WeChat from "node-socialite/dist/Providers/WeChat.js";
import { OfficialAccount } from 'node-easywechat';

class MyWeChat extends WeChat {
  constructor() {
    super();
    this._baseUrl = 'https://example.com';
  }
  // 重写其他相关方法
}

const app = new OfficialAccount({});
app.setOAuthFactory(function () {
  return (new MyWeChat({
    client_id: app.getAccount().getAppId(),
    client_secret: app.getAccount().getSecret(),
    redirect: app.getConfig().get('oauth.redirect_url'),
  })).scopes(app.getConfig().get('oauth.scopes', 'snsapi_userinfo'));
});

// 其它正常的业务逻辑
```
