### ISSUE TITLE
支付回调部分代码要咋写？

### ISSUE THREAD

**Issue by gitYuZui** [hpyer/node-easywechat#75]
## 我的环境 / My Environment
prisma
* Node 版本 / Version：18
* node-easywechat 版本 / Version：3.5
* 所用框架及版本 / Framework & Version：nestjs 10 + node-easywechat 3.5

## 问题描述 / Description the issue
我创建了个Pay模块Application实例
![image](https://github.com/hpyer/node-easywechat/assets/29330008/c7883020-4465-4de2-b1ed-5f680a8771bc)
但是在微信支付回调方法里面，我咋把拿到的请求数据经过handlePaid解密出来？我看了 easywechat那边的代码，他好像是底层封装好了吧。但是在nestjs框架下，request咋转成你模块下面的请求对象？这个不是很明白，
![image](https://github.com/hpyer/node-easywechat/assets/29330008/3e68496e-7c84-46f5-9ffc-5e7df7fff741)

**Comment by hpyer** [comment]
大概搜了下prisma的文档，这应该是个用来做数据访问层的工具，是没有封装request请求的。你看下你做web服务的是什么框架，koa，express还是其他？

**Comment by gitYuZui** [comment]
web框架用的是nestjs ，底层是express，可以拿到request

**Comment by gitYuZui** [comment]
我刚刚认真的看了一下你的代码。你代码中有个ServerRequest.createFromIncomingMessage 方法。是不是我直接把Request丢进去应该就可以转换了吧？
![image](https://github.com/hpyer/node-easywechat/assets/29330008/412c1825-3e22-4dda-bfd6-520c74368d30)

![image](https://github.com/hpyer/node-easywechat/assets/29330008/a5134126-0851-4edb-a290-7709e5ae77b9)

**Comment by hpyer** [comment]
对，就是这样。

我看你这代码貌似用的是 nest 框架，你在控制器里注入 `@Request` 的时候，要注意下这个 `Request` 是从 `express` 包引入的。

**Comment by gitYuZui** [comment]
好的。感谢！
