### ISSUE TITLE
公众号事件响应有问题。

### ISSUE THREAD

**Issue by gitYuZui** [hpyer/node-easywechat#78]
## 我的环境 / My Environment
node 18 + nestjs
* Node 版本 / Version：18
* node-easywechat 版本 / Version：3.5.1
* 所用框架及版本 / Framework & Version：3.5.1

## 问题描述 / Description the issue
请问一下。如何返回公众号消息？
按照文档以及easywechat的文档，我遵循了文档说明，定义了返回内容，并且确认了返回内容的正确性。但是不知道为啥公众号那边一直返回：该公众号提供的服务出现故障，请稍后再试。结果如下：
![image](https://github.com/hpyer/node-easywechat/assets/29330008/abba692f-50f1-424c-bc6d-d70fcb530d05)

![image](https://github.com/hpyer/node-easywechat/assets/29330008/c2ce157a-9780-4a81-a526-e35841bca839)
麻烦解答一下。感谢！
另外一个问题。能不能是点击了菜单之后，返回一个url回去。这个url我需要根据每一个用户的openId 来返回。

**Comment by hpyer** [comment]
1、`CustomReturnApiResponse` 这个对象封装后，最终的输出内容会变成啥？微信要求是返回 xml 格式内容。具体可以看下微信的文档：https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html

2、返回链接的话，直接返回带 `a` 标签的html内容就行。如：`感谢关注！<a href="https://example.com/test?openid">点击领取优惠券</a>`

**Comment by gitYuZui** [comment]
会返回结构体里面的原本内容。我在intercept中。将data提取出来了。
![image](https://github.com/hpyer/node-easywechat/assets/29330008/70c0a177-2ce1-453d-ab78-7b8470460067)

![image](https://github.com/hpyer/node-easywechat/assets/29330008/c6b3ea47-ec23-44ad-bd6e-3ebc7dca4b05)
![image](https://github.com/hpyer/node-easywechat/assets/29330008/6923d566-f40e-4b9f-ac4a-4fe0696f926d)

数据包：
![image](https://github.com/hpyer/node-easywechat/assets/29330008/ce295576-e50a-4cff-bf16-c9e6d4b65e37)

**Comment by hpyer** [comment]
你先查下token和aes_key是否跟公众号后台设置的一样。

如果一样，那要么就先调成明文模式，看下是否正常。

**Comment by gitYuZui** [comment]
我改成明文模式了。但是还是显示同样的错误。
![image](https://github.com/hpyer/node-easywechat/assets/29330008/21f68d69-2c26-4f0e-afdf-3967922a4a3c)

**Comment by gitYuZui** [comment]
是不是跟我这两个有关系？
![image](https://github.com/hpyer/node-easywechat/assets/29330008/95585fde-be98-4cac-8a73-a2a8475f7891)

**Comment by hpyer** [comment]
有可能，状态码改成200，content-type改成：text/xml 试试

**Comment by gitYuZui** [comment]
是的。我解决哈！ 确实是这个原因。 感谢感谢
修改后代码如下：
context
            .switchToHttp()
            .getResponse()
            .status(200)
            .setHeader('Content-Type', 'text/xml');

**Comment by gitYuZui** [comment]
另外就是。我的菜单的url链接。能不能让这个url变成动态url？ 例如通过事件回调。我返回一个url，然后用户那边就变成打开这个返回的url

**Comment by hpyer** [comment]
> 2、返回链接的话，直接返回带 `a` 标签的html内容就行。如：`感谢关注！<a href="https://example.com/test?openid">点击领取优惠券</a>`

这个没试么？

**Comment by hpyer** [comment]
另，你用的 node-easywechat 版本有点太旧了，方便的话最好升级下。

升级前，请先看下 [更新日志](https://github.com/hpyer/node-easywechat/blob/3.x/CHANGELOG.md)

**Comment by gitYuZui** [comment]
> > 2、返回链接的话，直接返回带 `a` 标签的html内容就行。如：`感谢关注！<a href="https://example.com/test?openid">点击领取优惠券</a>`
> 
> 这个没试么？

这种方式不行。因为我想在url中放入临时token。如果是这样子的话，token过期，消息还在。这样子会误导用户点击。

**Comment by gitYuZui** [comment]
> 另，你用的 node-easywechat 版本有点太旧了，方便的话最好升级下。
> 
> 升级前，请先看下 [更新日志](https://github.com/hpyer/node-easywechat/blob/3.x/CHANGELOG.md)

好的。感谢

**Comment by hpyer** [comment]
> 另外就是。我的菜单的url链接。能不能让这个url变成动态url？ 例如通过事件回调。我返回一个url，然后用户那边就变成打开这个返回的url

不好意思，之前没仔细看，误解了你的问题。

你这需求，用网页授权登录就可以实现了，参考下我 [demo](https://github.com/hpyer/node-easywechat-demo/blob/3.x/app.js) 里 `/wxlogin` 和 `/wxlogin/callback` 的代码。

[微信官方文档](https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html)
