### ISSUE TITLE
有时候会报错，没法追踪具体问题 

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#79]
"version": "3.6.3",
Error: Invalid Signature\n    at Validator.<anonymous> (/xxxx/node_modules/node-easywechat/dist/Pay/Validator.js:49:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/xxxxxx/node_modules/node-easywechat/dist/Pay/Validator.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)
不知道我写的代码哪里出问题，有时候会报这种错误， 没法追踪到我这边具体文件
希望能追踪到具体文件，

**Comment by hpyer** [comment]
你可以试着在处理消息前，把 `ServerRequest` 对象的内容（headers、querystring、body）打印到日志里，排查一下请求与其他正常请求是否一样。

**Comment by ValueLan** [comment]
> 你可以试着在处理消息前，把 `ServerRequest` 对象的内容（headers、querystring、body）打印到日志里，排查一下请求与其他正常请求是否一样。

  我试试看，主要是这个入口不好找，其次我模拟过错误的请求，报错方式不是这样。

**Comment by ValueLan** [comment]
https://github.com/hpyer/node-easywechat/blob/2dc88bce1ff0a7ab0a8e6ad805308fd336270561/src/Pay/Validator.ts#L42
如果当前服务器时间，比腾讯服务器时间慢10s，这个是不是会出问题

**Comment by ValueLan** [comment]
看了你源码，大概知道啥问题了，就看为什么出这个问题。我先关了，有问题再提

**Comment by ValueLan** [comment]
```
   return __awaiter(this, void 0, void 0, function* () {
            let cached = yield this.app.getCache().get(this.getCacheKey());
            if (cached) {
                return cached;
            }
            throw new Error('Credential "component_verify_ticket" does not exist in cache.');
        });
```
编译后的代码不好追踪错误
全部的报错如下 个人认为是 __awaiter  引起的
如果作为开发者，还是希望知道从哪个接口发起的错误，这样才能去比较方便的排查问题
Error: Credential "component_verify_ticket" does not exist in cache.
    at VerifyTicket.<anonymous> (xxx\serve\node_modules\node-easywechat\dist\OpenPlatform\Auth\VerifyTicket.js:33:19)
    at Generator.next (<anonymous>)
    at fulfilled (xxx\serve\node_modules\node-easywechat\dist\OpenPlatform\Auth\VerifyTicket.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ValueLan** [comment]
修复其实很简单
https://github.com/hpyer/node-easywechat/blob/2dc88bce1ff0a7ab0a8e6ad805308fd336270561/tsconfig.json#L6
改成 ES2020 只是不知道会不会影像其他人的低版本，

**Comment by hpyer** [comment]
你是在做开放平台的开发吗？这个 `component_verify_ticket` 是只要你在开放平台配置了服务端地址后，微信服务器会定时给你推送的，SDK包也会在接收到之后自动写到缓存里，后续再调用微信api的时候，也会自动加上，是不需要开发者去做任何处理的。

可以看下我demo里开放平台的代码。https://github.com/hpyer/node-easywechat-demo/blob/3.x/openplatform.js

**Comment by ValueLan** [comment]
可能你是误解我意思了，我意思是
 "target": "es6" 如果报错没法最终到错误入口
如果改成ES2020  可以追踪到入口
和开放平台没关系，只要代码源码里有await 后面的内容报错了 就没法追踪错误入口

如下所示  最终入口来自这里，
at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ValueLan** [comment]
下面两段代码都是源码编译出来的，
如果我使用ES2020编译后，就可以知道哪个入口调用这个方法报错的，
但是ES6 就没有办法
````
ES6编译结果， 使用了 yield  没法追踪
   // 如果 data 是 FormData 对象，则从中提取 headers
    if (options.data && options.data instanceof form_data_1.default) {
        options.headers = Object.assign(Object.assign({}, (yield this.getFormDataHeaders(options.data))), options.headers);
    }
  throw new Error("任意错误")
````



````
ES2020编译结果， 使用了 await 可以追踪
  // 如果 data 是 FormData 对象，则从中提取 headers
        if (options.data && options.data instanceof form_data_1.default) {
            options.headers = { ...(await this.getFormDataHeaders(options.data)), ...options.headers };
        }
  throw new Error("任意错误")

````

**Comment by ValueLan** [comment]
个人期望是把tsconfig.json 文件中的 compilerOptions.target 改成 es2020 但是对于我来说肯定没问题，我是nodejs20
你可能要考虑其他问题

**Comment by hpyer** [comment]
这个我回头测试下先吧，，得保证一些API需要的最低版本能正常运行。

**Comment by hpyer** [comment]
https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
查了下，node14就支持es2020了，我本地也跑了下测试用例，没问题。等下我就发布个新版本～

**Comment by hpyer** [comment]
请升级到 `v3.7.1`

**Comment by ValueLan** [comment]
非常感谢，我试试
