### ISSUE TITLE
Work AccessToken  gettoken 参数错误

### ISSUE THREAD

**Issue by curb-ui** [hpyer/node-easywechat#8]
Work AccessToken
'https://qyapi.weixin.qq.com/cgi-bin/gettoken'
参数与腾讯文档不对应
grant_type: 'client_credential',
appid: this.app.config.app_id,
secret: this.app.config.secret,

应为 https://work.weixin.qq.com/api/doc/90000/90135/91039
参数	必须	说明
corpid	是	企业ID，获取方式参考：术语说明-corpid
corpsecret	是	应用的凭证密钥，获取方式参考：术语说明-secret

**Comment by hpyer** [comment]
好的，晚点调整后，重新发一版～

**Comment by hpyer** [comment]
2.6.4修复了这个问题，看一下～

**Comment by curb-ui** [comment]
谢谢 可以了
