### ISSUE TITLE
是否支持微信公众号扫码登录功能？

### ISSUE THREAD

**Issue by QC2168** [hpyer/node-easywechat#81]

**Comment by hpyer** [comment]
1、这是业务层面的逻辑，需要你自行将生成二维码、扫码后的服务端处理等功能、逻辑串联起来，才能实现这个功能。
2、框架实现的是自动获取及管理access_token，ticket等关键数据，从而简化及统一微信api的调用和处理方式。

框架不会去封装这种业务层面的逻辑，所以它跟扫码登录没任何直接关系，但是你可以通过框架轻松的实现你需要的业务逻辑。

建议还是先去了解一下实现扫码登录的逻辑和原理。这里是一篇我找到的文章，你可以先看看：https://www.cnblogs.com/niumoo/p/18118422

**Comment by QC2168** [comment]
![image](https://github.com/hpyer/node-easywechat/assets/82024018/ca88d2fc-948b-412d-837e-02994c32e830)
那是不是图中的accessToken，ticket可以通过这个npm库来简化操作？
第9，10步的话，是不是得手动自己实现

**Comment by hpyer** [comment]
第2、7、9、10步都是需要你来实现的。第3、4是框架会自动完成，你无需关心。

**Comment by QC2168** [comment]
好的，谢谢您，我这边先研究下
