### ISSUE TITLE
微信支付这一块是否有更详细的文档

### ISSUE THREAD

**Issue by QC2168** [hpyer/node-easywechat#83]
## 问题描述 / Description the issue

我根据官方的文档来实现，发现很多是手动的，用easy-wechat这个库可以减少那一部分的操作？
![image](https://github.com/user-attachments/assets/25924e47-e870-4b6b-9e3d-bcaf68ae4231)

发现现在网上使用easywechat的教程使用的是4.x，5.0版本，貌似对不太上

**Comment by hpyer** [comment]
easywechat官网就有 6.x 的文档，https://easywechat.com/6.x/pay/

整个支付的流程就是这样，没办法简化的，SDK包主要是简化开发者对口的请求，不用过多的考虑签名、证书，异步通知时的消息解密等问题。可以更专注在业务逻辑上。

**Comment by QC2168** [comment]
那比如我现在请求这个接口（https://pay.weixin.qq.com/docs/merchant/apis/native-payment/direct-jsons/native-prepay.html），里面请求头有一项传入签名的，我还需要手动填入吗

**Comment by QC2168** [comment]
![image](https://github.com/user-attachments/assets/f2118e4e-ab95-4c95-bc4a-880324918a3a)

**Comment by hpyer** [comment]
不用额外去计算签名了，SDK包会自动完成签名

**Comment by QC2168** [comment]
好，那就是只处理传递的body参数就可以是吗

**Comment by QC2168** [comment]
![image](https://github.com/user-attachments/assets/7da763c2-1cd4-4608-997d-7a0370be21a3)
哥，我这一步应该是怎么做

**Comment by QC2168** [comment]
![image](https://github.com/user-attachments/assets/19d1acda-1063-4766-8476-bbd8497478f6)
我现在这边通过文档生成后是这两个文件，后面两个使用了

**Comment by hpyer** [comment]
你这两个文件，分配配置给 `certificate` 和 `private_key` 就可以。

至于 `platform_certs` 选项，`node-easywechat` 做了优化，可以不用配置，sdk包会自动去获取平台证书，并缓存。当然你也可以用注释里提到的工具，下载证书后，配置到这个 `platform_certs` 选项里也行。如：
```js
{
  // 商户号
  mch_id: 'test123',
  // 商户证书路径
  certificate: '/path/to/apiclient_cert.pem',
  // 商户证书私钥路径
  private_key: '/path/to/apiclient_key.pem',
  // 平台证书（v3接口需要）
  // 持路径列表或者PublicKey对象列表或者，以serial_no为key，证书内容或PublicKey对象为value的对象
  // 下载工具：https://github.com/wechatpay-apiv3/CertificateDownloader
  platform_certs: [
    '/path/to/platform_cert_1.pem',
    '/path/to/platform_cert_2.pem',
  ],
  // v3 API密钥
  secret_key: 'xxxxx',
}
```

**Comment by QC2168** [comment]
好的，谢谢大佬🌹已经配置好了！

**Comment by Choicelin** [comment]
> 你这两个文件，分配配置给 `certificate` 和 `private_key` 就可以。
> 
> 至于 `platform_certs` 选项，`node-easywechat` 做了优化，可以不用配置，sdk包会自动去获取平台证书，并缓存。当然你也可以用注释里提到的工具，下载证书后，配置到这个 `platform_certs` 选项里也行。如：
> 
> {
>   // 商户号
>   mch_id: 'test123',
>   // 商户证书路径
>   certificate: '/path/to/apiclient_cert.pem',
>   // 商户证书私钥路径
>   private_key: '/path/to/apiclient_key.pem',
>   // 平台证书（v3接口需要）
>   // 持路径列表或者PublicKey对象列表或者，以serial_no为key，证书内容或PublicKey对象为value的对象
>   // 下载工具：https://github.com/wechatpay-apiv3/CertificateDownloader
>   platform_certs: [
>     '/path/to/platform_cert_1.pem',
>     '/path/to/platform_cert_2.pem',
>   ],
>   // v3 API密钥
>   secret_key: 'xxxxx',
> }

牛的，那就是无需配置这个了，可以可以
