### ISSUE TITLE
文档疑惑

### ISSUE THREAD

**Issue by Choicelin** [hpyer/node-easywechat#87]
请问什么叫稳定版接口凭据，开启和不开启的区别是啥？

**Comment by Choicelin** [comment]
框架是个好框架，就是文档能跟上会比较好，原框架毕竟是PHP的，还是会有阅读的障碍

**Comment by hpyer** [comment]
这不是工具包的问题，微信官方文档就没怎么解释它俩的区别。

https://developers.weixin.qq.com/community/develop/doc/000ac4ccd90560e25a7f939f856400 根据这个帖子里官方的回复，以及微信官方文档（[AccessToken](https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Get_access_token.html)、[StableAccessToken](https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/getStableAccessToken.html)）来看，主要的区别是：

普通的token接口，在之前token未过期的情况下，重复调用会返回新的token，也会使之前的token失效；

而stable_token接口，在之前token未过期的情况下，重复调用则会返回之前未过期的token。同时，该接口增加了`force_refresh`参数，设置为true时，可以强制刷新stable_token。

**Comment by hpyer** [comment]
> 框架是个好框架，就是文档能跟上会比较好，原框架毕竟是PHP的，还是会有阅读的障碍

emmm...我抽空整理下文档，确实有些问题比较基础～

**Comment by Choicelin** [comment]
> 这不是工具包的问题，微信官方文档就没怎么解释它俩的区别。
> 
> https://developers.weixin.qq.com/community/develop/doc/000ac4ccd90560e25a7f939f856400 根据这个帖子里官方的回复，以及微信官方文档（[AccessToken](https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Get_access_token.html)、[StableAccessToken](https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/getStableAccessToken.html)）来看，主要的区别是：
> 
> 普通的token接口，在之前token未过期的情况下，重复调用会返回新的token，也会使之前的token失效；
> 
> 而stable_token接口，在之前token未过期的情况下，重复调用则会返回之前未过期的token。同时，该接口增加了`force_refresh`参数，设置为true时，可以强制刷新stable_token。

专家，厉害

**Comment by Choicelin** [comment]
> > 框架是个好框架，就是文档能跟上会比较好，原框架毕竟是PHP的，还是会有阅读的障碍
> 
> emmm...我抽空整理下文档，确实有些问题比较基础～

真的，完善的文档，做成国内2024年nodejs最好用的微信框架都是完全ok的
