### ISSUE TITLE
企业微信发送应用消息

### ISSUE THREAD

**Issue by curb-ui** [hpyer/node-easywechat#9]
缺少  markdown消息 
https://work.weixin.qq.com/api/doc/90000/90135/90236#markdown%E6%B6%88%E6%81%AF

小程序通知消息miniprogram_notice发送异常 参数与文档不一致
https://work.weixin.qq.com/api/doc/90000/90135/90236#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E9%80%9A%E7%9F%A5%E6%B6%88%E6%81%AF
`...
timeout: 30000,
baseURL: 'https://qyapi.weixin.qq.com/',
url: 'cgi-bin/message/send',
method: 'POST',
  data: {
    msgtype: 'miniprogrampage',
    agentid: 1000005,
    safe: 0,
    touser: 'XioaMing',
    miniprogrampage: {
      type: 'miniprogram_notice',
      appid: 'wx123123123123123',
      page: 'pages/index?userid=zhangsan&orderid=123123123',
      title: '会议室预订成功通知',
      description: '4月27日 16:16',
      emphasis_first_item: true,
      content_item: [Array]
    }
  },
  params: {
    access_token: '.........'
  },
...
`

**Comment by hpyer** [comment]
请更新2.6.5版本
