### ISSUE TITLE
被动回复图文消息是不是有BUG

### ISSUE THREAD

**Issue by snailzzj** [hpyer/node-easywechat#91]
## 我的环境 / My Environment

* Node 版本 / Version：v22
* node-easywechat 版本 / Version：3.x

## 问题描述 / Description the issue

server.with中return的是以下结构，前4个参数肯定是正确的，被动回复文字类型的消息是正常的。
但是被动回复图文类型时，article参数像下面这样写的话，微信会直接提示该公众号提供的服务出现故障，请稍后再试。

{
  ToUserName: 'xxx',
  FromUserName: 'xxx',
  CreateTime: '1722849707',
  MsgType: 'news',
  ArticleCount: 1,
  Articles: [
    {
      PicUrl: '有效图片url',
      Title: '标题',
      Description: '描述',
      Url: 'https://www.baidu.com'
    }
  ]
}

**Comment by hpyer** [comment]
数据结构错了，`Articles` 数组的元素中，还有一层`item`。 [微信文档](https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html#回复图文消息)

另，工具包会自动把请求中的 `ToUserName`、`FromUserName` 对调，然后写入回复消息里，也会自动添加 `CreateTime`，所以这三个字段可以不用设置。

回复图文消息示例：

```js
{
  MsgType: 'news',
  ArticleCount: 1,
  Articles: [
    {
      item: {
        Title: 'xxx',
        Description: 'xxx',
        PicUrl: 'xxx',
        Url: 'xxx'
      }
    }
  ],
}
```

**Comment by snailzzj** [comment]
感谢，测试正常了
