### ISSUE TITLE
params error in demo project

### ISSUE THREAD

**Issue by uctoo** [hpyer/node-easywechat#95]
## 我的环境 / My Environment

* Node 版本 / Version：
* node-easywechat 版本 / Version：
* 所用框架及版本 / Framework & Version：

## 问题描述 / Description the issue
![微信截图_20240910142749](https://github.com/user-attachments/assets/d2011a33-ec0d-4aa6-9b42-6e807cddd2ff)
公众号配置参数中的callback应为redirect_url

**Comment by hpyer** [comment]
感谢反馈，已修复
