### ISSUE TITLE
token or aes_key cannot be empty

### ISSUE THREAD

**Issue by ElshadBeg** [hpyer/node-easywechat#98]
## 我的环境 / My Environment

* Node 版本 / Version：v20.10.0
* node-easywechat 版本 / Version：3.7.5
* 所用框架及版本 / Framework & Version：nestjs10.x

## 问题描述 / Description the issue
小程序配置这块，说的是“aes_key，如果是明文模式，请不要填写”，但是不填写就会报错，这块可以看一看
`src/MiniApp/Application.ts`
里面的`getServer`方法的逻辑，希望能修复一下这个问题，谢谢！

**Comment by hpyer** [comment]
请更新`v3.7.6`

**Comment by ElshadBeg** [comment]
漂亮
